# Generated by Django 5.0.3 on 2024-03-14 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_product_image_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default='well_ecom/media/uploads/product/default.jpg', null=True, upload_to='uploads/product/'),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='well_ecom/media/uploads/product/default.jpg', null=True, upload_to='uploads/product/'),
        ),
    ]
