# Generated by Django 5.0.3 on 2024-03-14 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_category_image_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(default='well_ecom/media/uploads/product/default.png', null=True, upload_to='uploads/product/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='well_ecom/media/uploads/product/default.png', null=True, upload_to='uploads/product/'),
        ),
    ]
