# Generated by Django 5.0.3 on 2024-03-14 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_category_image_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(default='well_ecom/media/uploads/product/default.png', upload_to='uploads/product/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='well_ecom/media/uploads/product/default.png', upload_to='uploads/product/'),
        ),
    ]
