# Generated by Django 5.0.3 on 2024-03-15 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_category_image_alter_product_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
