# Generated by Django 5.0.3 on 2024-03-15 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(default='uploads/product/defualt_7zxLcLe.png', upload_to='uploads/product/'),
        ),
    ]
