# Generated by Django 5.0.3 on 2024-03-16 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='full_name_decs',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='well_ecom/media/uploads/product/default.png', upload_to='uploads/product/product-decs/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.product')),
            ],
        ),
    ]
