# Generated by Django 5.0.3 on 2024-03-16 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_product_full_name_decs_productimages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimages',
            old_name='image',
            new_name='image_1',
        ),
        migrations.AddField(
            model_name='productimages',
            name='image_2',
            field=models.ImageField(default='well_ecom/media/uploads/product/default.png', upload_to='uploads/product/product-decs/'),
        ),
        migrations.AddField(
            model_name='productimages',
            name='image_3',
            field=models.ImageField(default='well_ecom/media/uploads/product/default.png', upload_to='uploads/product/product-decs/'),
        ),
    ]
